<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>io.github.microsphere-projects</groupId>
        <artifactId>microsphere-observability-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../microsphere-observability-parent/pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.microsphere-projects</groupId>
    <artifactId>microsphere-observability-spring-cloud</artifactId>
    <version>${revision}</version>
    <packaging>jar</packaging>

    <name>Microsphere :: Observability :: Spring Cloud</name>
    <description>Microsphere Observability Spring Cloud</description>

    <dependencies>

        <!-- Microsphere Observability Spring Boot -->
        <dependency>
            <groupId>io.github.microsphere-projects</groupId>
            <artifactId>microsphere-observability-spring-boot</artifactId>
            <version>${revision}</version>
        </dependency>

        <!-- Microsphere Observability Metrics Spring Cloud -->
        <dependency>
            <groupId>io.github.microsphere-projects</groupId>
            <artifactId>microsphere-observability-metrics-spring-cloud</artifactId>
            <version>${revision}</version>
        </dependency>

    </dependencies>

</project>