<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>io.github.microsphere-projects</groupId>
        <artifactId>microsphere-observability-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../microsphere-observability-parent/pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.microsphere-projects</groupId>
    <artifactId>microsphere-observability-metrics-prometheus</artifactId>
    <version>${revision}</version>
    <packaging>jar</packaging>

    <name>Microsphere :: Observability :: Metrics :: Prometheus</name>
    <description>Microsphere Observability Metrics for Prometheus</description>

    <dependencies>

        <!-- Microsphere Annotation Processor -->
        <dependency>
            <groupId>io.github.microsphere-projects</groupId>
            <artifactId>microsphere-annotation-processor</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Microsphere Java Core -->
        <dependency>
            <groupId>io.github.microsphere-projects</groupId>
            <artifactId>microsphere-java-core</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Microsphere Alibaba Sentinel Commons -->
        <dependency>
            <groupId>io.github.microsphere-projects</groupId>
            <artifactId>microsphere-alibaba-sentinel-commons</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Alibaba Sentinel -->
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-core</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Prometheus Metrics Core -->
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>prometheus-metrics-core</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Prometheus Simpleclient(Legacy) -->
        <!-- https://prometheus.github.io/client_java/migration/simpleclient/ -->
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Testing -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Prometheus Metrics Instrumentation JVM -->
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>prometheus-metrics-instrumentation-jvm</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Prometheus Metrics Exporter HTTPServer -->
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>prometheus-metrics-exporter-httpserver</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- Logback -->
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>